export const token = {
  colorBrand: '#59BEA9',
  colorBrandLight: '#FAF5F3',
  colorBrandDark: '#000000',
  colorGray10: '#f7f7f7',
  colorGray20: '#efefef',
  colorGray30: '#e7e7e7',
  colorGray40: '#d6d6d6',
  colorGray50: '#bdbdbd',
  colorGray60: '#999999',
  colorGray70: '#7f7f7f',
  colorGray80: '#555555',
  colorGray90: '#333333',
  colorRed: '#c91630',
  colorRedDark: '#8c2a39',
  colorRedLight: '#ffb7c2',
  colorWhite: '#ffffff',
  fontFamilyDisplay: 'AvenirNext-Bold',
  fontFamilyText: 'AvenirNext-Regular',
  fontFamilyTextBold: 'AvenirNext-Bold',
  fontFamilyTextMedium: 'AvenirNext-Medium',
  fontFamilyTextDemiBold: 'AvenirNext-DemiBold',
  fontSizeHeader: 32,
  fontSizeHeaderLarge: 36,
  fontSizeHeaderSmall: 28,
  fontSizeMobileDisplay: 30,
  fontSizeMobileDisplayLarge: 52,
  fontSizeMobileDisplaySmall: 24,
  fontSizeMobileDisplayTiny: 20,
  fontSizeHuge: 24,
  fontSizeLarge: 20,
  fontSizeMedium: 16,
  fontSizeRegular: 14,
  fontSizeSmall: 12,
  fontSizeTiny: 10,
  fontWeightBold: '700',
  fontWeightDemiBold: '600',
  fontWeightMedium: '500',
  fontWeightRegular: '400',
  lineHeightHeader: 36,
  lineHeightHeaderLarge: 40,
  lineHeightHeaderSmall: 32,
  lineHeightHuge: 32,
  lineHeightLarge: 28,
  lineHeightMedium: 24,
  lineHeightMobileDisplay: 40,
  lineHeightMobileDisplayLarge: 58,
  lineHeightMobileDisplaySmall: 32,
  lineHeightMobileDisplayTiny: 30,
  lineHeightRegular: 24,
  lineHeightSmall: 20,
  lineHeightTiny: 16,
  opacityActiveDarken: 0.4,
  opacityActiveLighten: 0.4,
  opacityHoverDarken: 0.15,
  opacityHoverLighten: 0.2,
  radiusLarge: 8,
  radiusRegular: 5,
  radiusSmall: 3,
  sizeIconHeight: 24,
  sizeIconWidth: 24,
  sizeStatusBarHeight: 20,
  sizeUnsafeAreaHeightIPhoneX: 40,
  sizeTabBarHeight: 54,
  sizeThumbnailHeight: 60,
  sizeThumbnailWidth: 60,
  screenHeader: 60,
  spacingGiant: 52,
  spacingMega: 48,
  spacing40: 40,
  spacingHuge: 32,
  spacingLarge: 24,
  spacingHigh: 20,
  spacingSmallPlus: 12,
  spacingRegular: 16,
  spacingSmall: 8,
  spacingTiny: 4,
};

const mediumWeight = {
  fontFamily: token.fontFamilyTextMedium,
};
const demiBoldWeight = {
  fontFamily: token.fontFamilyTextDemiBold,
};
const boldWeight = {
  fontFamily: token.fontFamilyTextBold,
};

export const fonts = {
  display: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyDisplay,
    fontSize: token.fontSizeMobileDisplay,
  },
  displaySmall: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyDisplay,
    fontSize: token.fontSizeMobileDisplaySmall,
  },
  displayLarge: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyDisplay,
    fontSize: token.fontSizeMobileDisplayLarge,
  },
  header: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyTextBold,
    fontSize: token.fontSizeHeader,
    lineHeight: token.lineHeightHeader,
  },
  headerSmall: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyTextBold,
    fontSize: token.fontSizeHeaderSmall,
    lineHeight: token.lineHeightHeaderSmall,
  },
  huge: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyTextBold,
    fontSize: token.fontSizeHuge,
    lineHeight: token.lineHeightHuge,
  },
  title: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyTextMedium,
    fontSize: token.fontSizeLarge,
    lineHeight: token.lineHeightLarge,
  },
  medium: {
    ...mediumWeight,
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyTextMedium,
    fontSize: token.fontSizeMedium,
    lineHeight: token.lineHeightMedium,
  },
  regular: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyText,
    fontSize: token.fontSizeRegular,
    lineHeight: token.lineHeightRegular,
  },
  small: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyText,
    fontSize: token.fontSizeSmall,
    lineHeight: token.lineHeightSmall,
  },
  tiny: {
    color: token.colorBrandDark,
    fontFamily: token.fontFamilyText,
    fontSize: token.fontSizeTiny,
    lineHeight: token.lineHeightTiny,
  },
  boldWeight,
  demiBoldWeight,
  mediumWeight,
};

export const dropShadow = {
  // There is no token for pure black color
  shadowColor: 'rgb(0,0,0)',
  shadowOffset: {
    width: 0,
    height: 3,
  },
  shadowOpacity: 0.15,
  shadowRadius: token.radiusSmall,
};

export const animations = {
  buttons: {
    activeOpacity: 0.85,
  },
};
